---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: Resolve incident
    servicenow.itsm.incident:
      state: resolved
      number: INC0010001
      close_code: "Solved (Permanently)"
      close_notes: "Resolved"
      
  - name: Close incident
    servicenow.itsm.incident:
      state: closed
      number: INC0010001
      close_code: "Solved (Permanently)"
      close_notes: "Closed"
