---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Create incident
    servicenow.itsm.incident:
      state: new
      caller: some.user
      short_description: User is not receiving email
      description: User has been unable to receive email for the past 15 minutes
      attachments:
        - path: path/to/attachment.txt
      impact: low
      urgency: low

      other:
        expected_start: 2021-02-12

