---
- name: Create new ServiceNow incident
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: Create incident
    servicenow.itsm.incident:
      state: "{{ snticket_state | default('new') }}"
      caller: "{{ snticket_caller | default(omit) }}"
      short_description: "{{ snticket_shdesc | default('created by an Ansible playbook but missing a short description') }}"
      description: "{{ snticket_desc | default(omit) }}"
      impact: "{{ snticket_impact | default('low') }}"
      urgency: "{{ snticket_urgency | default('low') }}"
      other:
        expected_start: "{{ sn_slastart | default('2022-01-01) }}"
    register: sn_created

  - name: spit out the info from the new incident
    debug:
      var: "{{ sn_created }}"
