---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: Resolve incident
    servicenow.itsm.incident:
      state: resolved
      number: "{{ sn_inci_number | default('INC0000000') }}"
      close_code: "Solved (Permanently)"
      close_notes: "Resolved"
      
  - name: Close incident
    servicenow.itsm.incident:
      state: closed
      number: "{{ sn_inci_number | default('INC0000000') }}"
      close_code: "Solved (Permanently)"
      close_notes: "{{ sn_inci_closenotes | default('Closed') }}"
